<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cbo_ComboBox</name>
   <tag></tag>
   <elementGuidId>c80db10f-57e6-4896-95d3-5b7c7c096fc5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//td[normalize-space(text())='${label}']/following::td[1]/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//td[normalize-space(text())='${label}']/following::td[1]/select</value>
   </webElementProperties>
</WebElementEntity>
