<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_Textbox</name>
   <tag></tag>
   <elementGuidId>f83dda9d-6f51-4b80-a424-0d3e437db195</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//td[normalize-space(text())='${label}']/following::td[1]/input[@type='text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//td[normalize-space(text())='${label}']/following::td[1]/input[@type='text']</value>
   </webElementProperties>
</WebElementEntity>
