<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mnu_Item</name>
   <tag></tag>
   <elementGuidId>90eaf1c4-6b0f-4896-9a93-342bde1ff986</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[normalize-space(.)='${itemName}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[normalize-space(.)='${itemName}']</value>
   </webElementProperties>
</WebElementEntity>
