<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chk_Checkbox</name>
   <tag></tag>
   <elementGuidId>700f8fdd-16aa-49c0-bfbf-8a31fc561b7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[normalize-space(text())='${label}']/following::input[1][@type='checkbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[normalize-space(text())='${label}']/following::input[1][@type='checkbox']</value>
   </webElementProperties>
</WebElementEntity>
