<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iFrame</name>
   <tag></tag>
   <elementGuidId>b3bece90-4980-42b5-b61f-b767c9735370</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//frame[${index}]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//frame[${index}]</value>
   </webElementProperties>
</WebElementEntity>
