<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cbo_OptionGroup</name>
   <tag></tag>
   <elementGuidId>9dd24314-be2c-4e8d-ad80-9e5fef601b45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//mat-select[@aria-label='Pokemon']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//mat-select[@aria-label='Pokemon']</value>
   </webElementProperties>
</WebElementEntity>
